language: objective-c
osx_image: xcode7.1
install:
- npm install -g playground

env:
  matrix:
    secure: a2fi02GPkxw27jVjW47EkvB/BW/SOIxlmLQJaiZ3xqbKe4udUxKE0ZigD0nVJDmxpiVHv5/Uc9ZQDPtKvvmU9kakusxjBVqMy+IxCYsH4+aDaATdaY9WHvVbARXJGjE/KmKnTfos/P8G8XqXahNKznql/gF2wZNoQIQD49JNk8s=

script:
- make
- rm -rf CommonCrypto
- ./GenerateCommonCryptoModule iphonesimulator9.0 .
- cat CommonCrypto/module.map
- pwd
- xcodebuild build -scheme IDZSwiftCommonCrypto -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0'
- make test
