language: objective-c

install:
- npm install -g swift-playground-builder

script:
# Generate README.playground from README.md
- make
- git add .
- git commit -m"Playground update from Travis [ci skip]"
- git push
- pushd IDZSwiftCommonCrypto
- rm -rf CommonCrypto
- ./GenerateCommonCryptoModule iphonesimulator8.0 .
- cat CommonCrypto/module.map
- pwd
- xcodebuild build -scheme IDZSwiftCommonCrypto -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.0'
# Remove testing pending solution to https://github.com/travis-ci/travis-ci/issues/2829
#- xcodebuild test -scheme IDZSwiftCommonCrypto -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.0'
- popd
